name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*", "dev"]

jobs:
  run_tests_ubuntu:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install -e .
          pip install pytest
          pip install pytest-cov[toml]
          pip install nbmake
          pip install rootutils

      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run tests
        run: |
          pytest -v --doctest-modules --cov EventStream --ignore docs/ --nbmake

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
